apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tw015f2ks-go 
  janus-idp.io/tekton: tw015f2ks-go
  backstage.io/kubernetes-id: tw015f2ks-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tw015f2ks-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml